basePath: /api/v1
info:
  contact: {}
paths:
  /exercise/users:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: user
      summary: ping exercise
      tags:
      - example
swagger: "2.0"
